### ISSUE TITLE
Ошибка обработки URL с параметрами запроса без значений

### ISSUE THREAD

**Issue by vbondarevsky** [vbondarevsky/Connector#10]
Например,
`https://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?wsdl`

**Comment by xxxPavel** [comment]
Не работает

**Comment by leemuar** [comment]
> Не работает если этот параметр число https://www.cbr.ru/DailyInfoWebServ/DailyInfo.asmx?10

Показывайте код, который не работает

**Comment by xxxPavel** [comment]
![изображение_2023-12-31_131806664](https://github.com/vbondarevsky/Connector/assets/155271798/389ece68-7a02-4662-ad57-0f9d8ec2b693)

**Comment by leemuar** [comment]
Решено в #135 благодаря [alexandr-yang](https://github.com/alexandr-yang). Спасибо ему!
