### ISSUE TITLE
Отказаться от использования httpbin.org в пользу своей инсталляции

### ISSUE THREAD

**Issue by vbondarevsky** [vbondarevsky/Connector#100]
сейчас httpbin.org некорректно обрабатывает редиректы
до этого тоже была куча проблем с переходами http->https->http

Своя инсталляция даст возможность добавить свои тесты

**Comment by zeegin** [comment]
https://httpbingo.org/

???

**Comment by vbondarevsky** [comment]
> https://httpbingo.org/
> 
> ???

У него пока что еще меньше функций, чем у оригинального httpbin
