### ISSUE TITLE
Не заполняется тело запроса при PUT

### ISSUE THREAD

**Issue by malikov-pro** [vbondarevsky/Connector#106]
Так работает
```
СтрокаДанные = КоннекторHTTP.ОбъектВJson(СтруктураДанные);
ДополнительныеПараметры.Вставить("Данные", СтрокаДанные);
ОтветОбновление = КоннекторHTTP.Put(СтрокаЗапроса, ,ДополнительныеПараметры);
```

Так не работает
СтрокаДанные = КоннекторHTTP.ОбъектВJson(СтруктураДанные);
ОтветОбновление = КоннекторHTTP.Put(СтрокаЗапроса, СтрокаДанные, ДополнительныеПараметры);

При том что в POST отрабатывает нормально (проверю еще раз)

**Comment by leemuar** [comment]
@malikov-pro проверили?
