### ISSUE TITLE
Выполнение JS-кода при загрузке страницы

### ISSUE THREAD

**Issue by antonwantstosleep** [vbondarevsky/Connector#108]
Здравствуйте!

Есть страница https://fgis.gost.ru/fundmetrology/cm/results/1-104128293. Если сделать GET курлом или методом вашей библиотеки, то в ответ приходит вот это:
```
$ curl https://fgis.gost.ru/fundmetrology/cm/results/1-104128293
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <base href="/fundmetrology/cm/">
  <title>РСТ МЕТРОЛОГИЯ</title>
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <link rel="icon" href="favicon.ico">
  <link href="/fundmetrology/cm/assets/app.8b777ac7.css" rel="stylesheet" type="text/css"/>
</head>
<body>
<div id="app"></div>
</body>
<script src="/fundmetrology/cm/assets/app.b63e60ed.js"></script>
</html>
```
Как вы понимаете, в `<div id="app"></div>` должны быть данные, но они появляются только в браузере.

Можно ли сделать что-то, чтобы страница загрузилась полностью? Как "стрельнуть" скрипт `app.b63e60ed.js` и последующие за ним скрипты?

Спасибо!

**Comment by vbondarevsky** [comment]
Ну собственно в полученной странице ищем `script src="..."`. Это относительные пути.
Далее
`КоннекторHTTP.Get("https://fgis.gost.ru + полученные пути")`
