### ISSUE TITLE
Ошибка при запросах с аутентификацией в мобильном приложении

### ISSUE THREAD

**Issue by pravets** [vbondarevsky/Connector#111]
При попытке совершить запрос с аутентификацией в мобильном приложении происходит ошибка в строке
https://github.com/vbondarevsky/Connector/blob/af9c38c28d0f3f50902d2e7a1593c26f130ea671/src/ru/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L1262
В строке ожидается Структура, а приходит Соответствие.

Проблема возникает из-за метода Скопировать

https://github.com/vbondarevsky/Connector/blob/af9c38c28d0f3f50902d2e7a1593c26f130ea671/src/ru/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L3297

В результате выполнения JsonВОбъект(ОбъектВJson(Источник)) по умолчанию получается на выходе Соответствие, даже если на входе была Структура.

В свою очередь копирование вызывается здесь 
https://github.com/vbondarevsky/Connector/blob/af9c38c28d0f3f50902d2e7a1593c26f130ea671/src/ru/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L1139

Для себя набросал решение:

Если ТипЗнч(Источник) = Тип("Структура") Тогда 	
	Возврат JsonВОбъект(ОбъектВJson(Источник),, Новый Структура ("ПрочитатьВСоответствие", Ложь));	
Иначе	
	Возврат JsonВОбъект(ОбъектВJson(Источник));	
КонецЕсли;

**Comment by leemuar** [comment]
Исправлено в #136
