### ISSUE TITLE
Результат postjson в структуру

### ISSUE THREAD

**Issue by a-sitnikov** [vbondarevsky/Connector#112]
Как по простому указать что результат нужно получать в структуру, а не в соответствие
По идее нужно задать правила преоброзования, но сам метод новых правил по умолчанию не экспортный.
Да и такая конструкция не особо удобна.
Хотелось быть отдельную опцию в доп параметрах

**Comment by vbondarevsky** [comment]
> Как по простому указать что результат нужно получать в структуру, а не в соответствие По идее нужно задать правила преоброзования, но сам метод новых правил по умолчанию не экспортный. Да и такая конструкция не особо удобна. Хотелось быть отдельную опцию в доп параметрах

Документация
https://github.com/vbondarevsky/Connector/blob/af9c38c28d0f3f50902d2e7a1593c26f130ea671/src/ru/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L358-L360

Пример
https://github.com/vbondarevsky/Connector/blob/af9c38c28d0f3f50902d2e7a1593c26f130ea671/src/ru/DataProcessors/%D0%A2%D0%B5%D1%81%D1%82%D1%8B/Ext/ObjectModule.bsl#L550-L552

@a-sitnikov
