### ISSUE TITLE
charset в Content-type

### ISSUE THREAD

**Issue by agalanov-ozon** [vbondarevsky/Connector#115]
Есть вопрос по автозаполнению поля content-type
Например здесь https://github.com/vbondarevsky/Connector/blob/master/src/ru/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L1296
Оно выставляется в "application/json". Не будет ли лучше ставить его в "application/json;charset=utf-8", учитывая что через строку мы делаем
HTTPЗапрос.УстановитьТелоИзСтроки(СтрокаJson, КодировкаТекста.UTF8, ИспользованиеByteOrderMark.НеИспользовать); И там utf-8?

Столкнулись с проблемой, что когда у нас запросы пошли через прокси, то начала ломаться кодировка без явного указания charset

**Comment by vbondarevsky** [comment]
fixed
