### ISSUE TITLE
Поддержка работы с облаками S3

### ISSUE THREAD

**Issue by Diversus23** [vbondarevsky/Connector#116]
Добрый день!
Очень рад, что есть такая замечательная библиотека для работы с вебом. Снимает кучу головной боли.
Интересует вопрос: планируете ли реализацию работы с облаками S3?
Лично нуждаюсь в этом, т.к. нужна возможность отправки/скачивания файлов на S3 через OneScript и было бы здорово, если бы это появилось.
Спасибо за вашу работу!

**Comment by BlizD** [comment]
Мы уже использовали у себя коннектор для связи с s3 все норм работает

**Comment by Diversus23** [comment]
> Мы уже использовали у себя коннектор для связи с s3 все норм работает. По идее ничего дорабатывать не нужно, коннектор уже умеет это.

А где конкретно? Где можно код посмотреть? Спасибо

**Comment by BlizD** [comment]
https://github.com/BlizD/S3_SSL/blob/main/src/CommonModules/s3_API/Ext/Module.bsl

**Comment by BlizD** [comment]
Завтра могу еще пример скинуть

**Comment by Diversus23** [comment]
Вау. Да вы молодцы! :)
Целая подсистема для замены на сетевое хранилище. Интересно, почему 1С аналогичное не сделает в типовых?

**Comment by BlizD** [comment]
@Diversus23 вроде уже анонсировали это, недавно видел это где то. 
Плюс во фреше мне кажется это уже давно было реализовано.

**Comment by BlizD** [comment]
Поддержка внешних хранилищ двоичных данных по протоколу S3

https://wonderland.v8.1c.ru/blog/plan-zadach-na-versiyu-8-3-24-platformy-1s-predpriyatie/
