### ISSUE TITLE
поддержка функций

### ISSUE THREAD

**Issue by EvenRow** [vbondarevsky/Connector#117]
Здравствуйте!
Кто нибудь знает, а можно ли в данной библиотеке передавать в качестве параметров функции в теле запроса? Например, по типу API MS Dynamics, где указывается ресурс, а далее в параметры нужно передать что то подобное: ?$select=big_externalid&$filter=**contains**(big_externalid,'dfc64486-691c-11e2-8074-0024e84ab328') **or** **contains**(big_externalid,'dfc64487-691c-11e2-8074-0024e84ab328'), где жирным выделены функции API.

**Comment by vbondarevsky** [comment]
Можно прямо в URL указывать или через параметры

```
ПараметрыЗапроса = Новый Соответствие;
ПараметрыЗапроса.Вставить("$select", "big_externalid");
ПараметрыЗапроса.Вставить("$filter", "contains(big_externalid,'dfc64486-691c-11e2-8074-0024e84ab328') or contains(big_externalid,'dfc64487-691c-11e2-8074-0024e84ab328')");
	
Ответ = КоннекторHTTP.Post(URL, ПараметрыЗапроса, ДополнительныеПараметры);	
```
