### ISSUE TITLE
Ошибка GET при S3 подключении. HTTPЗапрос.Тело запроса

### ISSUE THREAD

**Issue by maximsamokhval** [vbondarevsky/Connector#119]
**Дано**:

- Платформа 8.3.20.1549 и выше
- Зарегистрированный аккаунт на digital ocean spaces (s3 storage)

**Вызываю метод GET** 
	
``` bsl

	Аутентификация = Новый Структура;
	Аутентификация.Вставить("Тип", "AWS4-HMAC-SHA256");
	Аутентификация.Вставить("ИдентификаторКлючаДоступа", 	s3_ИдентификаторКлючаДоступа); 
	Аутентификация.Вставить("СекретныйКлюч", 				s3_СекретныйКлюч);
	Аутентификация.Вставить("Регион", 						s3_Регион);
	Аутентификация.Вставить("Сервис", 						"s3");

	ДополнительныеПараметры 	= Новый Структура;              
	ДополнительныеПараметры.Вставить("Аутентификация", Аутентификация);
	URL 					= Хост+"perfmon.pdf";
	
	HTTPОтвет = inКоннекторHTTP.Get(URL,,ДополнительныеПараметры);

```
**Ожидаю** 	
HTTPОтвет.КодОтвета = 200

**Фактический результат**
HTTPОтвет.КодОтвета = 501

``` xml

<?xml version="1.0" encoding="UTF-8"?><Error>
<Code>NotImplemented</Code>
<RequestId>tx00000000000003ecdcb1e-0063f4bc9f-58e4b92d-nyc3c</RequestId>
<HostId>58e4b92d-nyc3c-nyc3-zg03</HostId>
</Error>

```

Место возникновения ошибки

![image](https://user-images.githubusercontent.com/24194977/220349013-ea4ae13c-a410-4be9-a696-3b0de552b07c.png)

До вызова метода `ПолучитьТелоКакПоток()`  `HTTPЗапрос.ПолучитьТелоКакСтроку()` возвращает значение Неопределено
После вызова = "" ( пустая строка) 

![image](https://user-images.githubusercontent.com/24194977/220349325-39949ccf-d78e-4e91-be66-49fde73f938f.png)

![image](https://user-images.githubusercontent.com/24194977/220349349-51456786-45b7-4cea-9686-9b54123f7215.png)

``` bsl 

ПодготовленныйЗапрос.Заголовки["x-amz-content-sha256"] = 
		ХешированиеДанных(ХешФункция.SHA256, ПодготовленныйЗапрос.HTTPЗапрос.ПолучитьТелоКакПоток()); 

```

Ошибка возникает на вызове метода GET и на платформах 8.3.20.*

На платформе 8.3.16.1814 метод отрабатывает корректно

**Comment by BlizD** [comment]
В Postman метод выполняется? Пришлите скрин

**Comment by BlizD** [comment]
С S3 уже несколько раз работали и проблем не было. Если в Postman работает, то и в 1с должно

**Comment by BlizD** [comment]
Посмотрите может помогут примеры кода 
https://github.com/BlizD/S3_SSL/blob/main/src/CommonModules/s3_API/Ext/Module.bsl

**Comment by maximsamokhval** [comment]
> В Postman метод выполняется? Пришлите скрин

Во вложении пример из Postman

![image](https://user-images.githubusercontent.com/24194977/220665207-2019dfac-423e-4473-8a13-86b307d5a669.png)

Как раз Ваши примеры и взял за основу, но, как я и писал, что проблема в платформе 8.3.20.1549
Если повторить на платформе 8.3.16.1814 проблем нет.

**Comment by maximsamokhval** [comment]
> 

Я один и тот же код выполняю на разных платформах и получаю **разный** результат.
Библиотека одинаковая, обработка идентична, в Postman работает.





**1С:Предприятие 8.3 (8.3.16.1814)**
![image](https://user-images.githubusercontent.com/24194977/220667259-9a0d32f8-195b-45dd-96f5-bb3f462594de.png)


**1С:Предприятие 8.3 (8.3.20.1549)**
![image](https://user-images.githubusercontent.com/24194977/220668066-71ba1ec2-fa85-4fc0-b220-89a00f230c3c.png)


Платформа при вызове метода  `ПодготовленныйЗапрос.HTTPЗапрос.ПолучитьТелоКакПоток()` устанавливает в тело запроса пустую строку ( видно на скрине )


![image](https://user-images.githubusercontent.com/24194977/220669073-7a25a035-92dd-4fce-9d27-76f8c61d9ee5.png)


Платформа 8.3.16.1814 обрабатывает после этого запрос типа GET нормально и сервер возвращает 200 код, то платформа 8.3.20.1549 при таком же запросе отрабатывает некорректно - сервер возвращает 


![image](https://user-images.githubusercontent.com/24194977/220670999-ca440f1a-5790-4d35-a5a3-aacc03c561a6.png)

**Comment by BlizD** [comment]
Ну тогда, скорее всего проблема не в Коннекторе, а в ошибке в платформы.
А на последней платформе 1с, ошибка сохраняется?

Попробуйте еще создать S3 на облаке mail.ru - может все таки это особенность Вашего сервера S3, а не платформы 1с или библиотеки.

**Comment by maximsamokhval** [comment]
> Ну тогда, скорее всего проблема не в Коннекторе, а в ошибке в платформы. А на последней платформе 1с, ошибка сохраняется?
> 
> Попробуйте еще создать S3 на облаке mail.ru - может все таки это особенность Вашего сервера S3, а не платформы 1с или библиотеки.

Да, я запустил локально minio и все завелось.
Видимо digital ocean по другому обрабатывает запросы
Тогда это скорее особенность s3 сервера
