### ISSUE TITLE
Параметры запроса при создании структуры новых параметров.

### ISSUE THREAD

**Issue by Untru** [vbondarevsky/Connector#120]
Это баг или фитча?
Если написать 
	ПараметрыЗапроса = Новый Структура;
	ПараметрыЗапроса.Вставить("Параметр1", Параметр1);
	
        ДопПараметры = КоннекторHTTP.НовыеПараметры();
	ДопПараметры.Заголовки.Вставить .......;

УИ_КоннекторHTTP.Get(URLЗапроса, ПараметрыЗапроса, ДопПараметры);

ПараметрыЗапроса игнорируются, работают только если написать 
ДопПараметры.ПараметрыЗапроса  = ПараметрыЗапроса ;
Но тогда я не понимаю смысл второго параметра.

**Comment by Untru** [comment]
увидел пулл реквест
https://github.com/vbondarevsky/Connector/pull/103 как раз с моей проблемой, какова его судьба?)
он будет принят?)

**Comment by vbondarevsky** [comment]
Пофиксил
