### ISSUE TITLE
Зачем в расширении контролируется свойство "Назначение использования"?

### ISSUE THREAD

**Issue by john-doe-1c** [vbondarevsky/Connector#126]
Из-за этого расширение не подключается почти ни к какой типовой, например БП 3:

![image](https://github.com/vbondarevsky/Connector/assets/75837433/337317d8-617b-4852-a6a3-d8f006655883)

Приходится через конфигуратор отключать в расширении контроль этого свойства.

**Comment by leemuar** [comment]
Исправлено
