### ISSUE TITLE
Сжатие GZip отправляемых данных планируется ?

### ISSUE THREAD

**Issue by itopt** [vbondarevsky/Connector#13]

**Comment by vbondarevsky** [comment]
А примеры для чего это может быть нужно?

**Comment by itopt** [comment]
Столкнулся с тем, что надо периодически выгружать из 1с на внешний сервис довольно большой объем информации (около 300-800 мб в не сжатом виде), а сервис понимает только gzip, но 1с в gzip не умеет просто так. Увидел в вашей реализации работу с двоичными данным чтобы из gzip сделать zip, а мне нужно собственно наоборот и поменьше костылей в виде ВК или еще чего.

**Comment by vbondarevsky** [comment]
В рамках этой библиотеки точно нет

**Comment by vbondarevsky** [comment]
@itopt вдруг еще актуально. Сжатие отправляемых данных появилось
