### ISSUE TITLE
Работа с HTTP API Amazon

### ISSUE THREAD

**Issue by vbondarevsky** [vbondarevsky/Connector#14]

**Comment by ArchLord42RU** [comment]
Какие тут планы? У меня есть наработки по работе с Amazon S3 из 1С например, могу поделится :)

**Comment by vbondarevsky** [comment]
По сути код у меня уже написан, пока не было времени все это дело интегрировать.
Скорей это будет отдельная библиотека на базе Коннектора

**Comment by best-tech** [comment]
сейчас вроде есть аутентификация S3, но работает она странно, объект создавать позволяет а корзины нет, в чем может быть дело?

**Comment by vbondarevsky** [comment]
> сейчас вроде есть аутентификация S3, но работает она странно, объект создавать позволяет а корзины нет, в чем может быть дело?

А код можно увидеть?
