### ISSUE TITLE
Невозможность создания параметров запроса с некоторыми символами

### ISSUE THREAD

**Issue by makar47** [vbondarevsky/Connector#144]
1. 
```
ПараметрыЗапроса = Новый Структура;
ПараметрыЗапроса.Вставить("filter[ID]", 123);
```
нельзя создать такой параметр запроса, из-за ограничений "Структуры" 1С:

> Первым символом ключа должна быть буква или символ подчеркивания (\_).
> Каждый из последующих символов может быть буквой, цифрой или символом подчеркивания (\_).

Можно обойти это ограничение указав такой параметр напрямую в строке адреса.

2.
Если указать в строке адреса параметр вида
`filter[>%3DDATE_CREATE]=2024-01-01`
он будет в результате преобразован к виду
`filter[>=DATE_CREATE]=2024-01-01` и разобран неправильно на 

> Ключ: `filter[>`
> Значение: `DATE_CREATE] =2024-01-01`

**Comment by leemuar** [comment]
@makar47 попробуйте вместо структуры передать соответствие. Коннектор это умеет обрабатывать. Отпишитесь получилось или нет

**Comment by makar47** [comment]
Да, с соответствием все работает! Спасибо!
```
ПараметрыЗапроса = Новый Соответствие();
ПараметрыЗапроса.Вставить("filter[>%3DDATE_CREATE]", датаНачала);
```
