### ISSUE TITLE
Не обрабатываются ошибки сервера

### ISSUE THREAD

**Issue by Antonio1C** [vbondarevsky/Connector#146]
Когда вызываешь функции GetJson, PutJson и другие подобные, в случае внутренних ошибок сервера (500) код падает, так как не проверяет на корректный статус ответа и пытается преобразовать его в Json.

**Comment by leemuar** [comment]
Обсуждали. Не используйте функции с суффиксом Json, если вам нужна не простая обработка ошибок и ответа.
Эти функции - удобный фасад для простых случаев. Если есть шанс не получить JSON в ответе - используйте функции без суффикса и пишите всю логику проверок руками
