### ISSUE TITLE
Новый релиз

### ISSUE THREAD

**Issue by alexandr-yang** [vbondarevsky/Connector#148]
Давайте сделаем новый релиз, а то последний был в 2020 году. Библиотека выглядит заброшенной (есть нюансы, но это не совсем так). Судя по всему нужно еще синкануть ru и en версии, чтобы все было красиво. Хотя это спорный момент, раньше en в релизах не было.

**Comment by TELSCARGO** [comment]
Насчет релиза поддерживаю

**Comment by leemuar** [comment]
Готово: https://github.com/vbondarevsky/Connector/releases/tag/v2.6.0
