### ISSUE TITLE
Работа из клиентского контекста планируется ?:)

### ISSUE THREAD

**Issue by ArchLord42RU** [vbondarevsky/Connector#16]
В данный момент модуль является чисто серверным, планируется ли сделать клиент-серверный вариант?

**Comment by vbondarevsky** [comment]
А зачем?

Сходу вижу такие проблемы:
- на клиенте не работают `КодироватьСтроку`, `РаскодироватьСтроку`, `ХешированиеДанных`
- в веб-клиенте не работает все что связано с `HTTP`, `JSON`

Ну для первого можно что-то накодировать на встроенном языке.
Для второго нужно писать внешнюю компоненту.

Кажется много мороки, а выхлоп близок к 0
