### ISSUE TITLE
Ошибка кодирования параметров запроса GET

### ISSUE THREAD

**Issue by rsyuzyov** [vbondarevsky/Connector#20]
Владимир, прежде всего преогромнейшее спасибо за чудесную библиотеку!

Воспроизведение ошибки:
1. Ставим точку останова в методе ВызватьHTTPМетод после строки:
ПодготовленныйЗапрос = ПодготовитьЗапрос(Сессия, Запрос);
2. Выполним код:
КоннекторHTTP.GetJson("http://localhost/query", Новый Структура("date", Формат(Дата('20191103'), "ДФ=yyyy-MM-ddTHH:mm:ss.000000")))

В результате в ПодготовленныйЗапрос.HTTPЗапрос.АдресРесурса получим:
/query?date=2019-11-03T00:00:00.000000
Хотя ожидается:
/query?date=2019-11-03T00%3A00%3A00.000000

Где уши: метод КодироватьПараметрыЗапроса, строка:
ЗначениеПараметра = КодироватьСтроку(Значение, СпособКодированияСтроки.URLВКодировкеURL);

Исправление:
-ЗначениеПараметра = КодироватьСтроку(Значение, СпособКодированияСтроки.URLВКодировкеURL);
+ЗначениеПараметра = КодироватьСтроку(Значение, СпособКодированияСтроки.КодировкаURL);

**Comment by vbondarevsky** [comment]
Ну это не то чтобы прям ошибка, данном случае можно и так и так.
Но все равно поправил

**Comment by rsyuzyov** [comment]
Да вот Тиньковцы, хоть и молодцы в целом, но точки проглотить не смогли)). Спасибо!

**Comment by VolAll** [comment]
Получил похожую ошибку но в другом контекте
/Authenticate?login=m47*@87687996.ru&password=A345642020
конвертируется в 
/Authenticate?login=m47*%4087687996.ru&password=A345642020

конвертация знака @  в %40

итог не прохожу авторизацию.

**Comment by VolAll** [comment]
Прошу прощения,  разобрались. проблема была на беке куда отправлял запрос.
