### ISSUE TITLE
Возможность переопределять дату AWS4 запроса

### ISSUE THREAD

**Issue by leemuar** [vbondarevsky/Connector#31]
Не могу придумать реального случая, когда это может пригодиться, кроме отладки. В данный момент всегда берется текущая дата:

https://github.com/vbondarevsky/Connector/blob/5865ff4621752d1e9b0fffb1b76fff5fc4e8a307/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L1912

Варианты:
- анализировать заголовки запроса, если в них есть ```x-amz-date``` или ```date``` - использовать их значение
- еще один параметр аутентификации^
```
Аутентификация = Новый Структура;
Аутентификация.Вставить("ДатаЗапроса", Дата(2020, 02, 01));
...
```

**Comment by vbondarevsky** [comment]
Дату можно задать через заголовок
https://github.com/vbondarevsky/Connector/blob/e8d6225530db445cb36a59e1772bfab4403ddcb3/src/DataProcessors/%D0%A2%D0%B5%D1%81%D1%82%D1%8B/Ext/ObjectModule.bsl#L843
