### ISSUE TITLE
Передача параметров-массивов с [] в именах

### ISSUE THREAD

**Issue by FragsterAt** [vbondarevsky/Connector#32]
Возможно, опционально. В общем, 
```bsl
ПараметрыЗапроса = Новый Структура;
ПараметрыЗапроса.Вставить("param", СтрРазделить("1,2", ","));

Ответ = КоннекторHTTP.GetJson("https://httpbin.org/anything/params", ПараметрыЗапроса);	
```
должна быть возможность отправить не только `https://httpbin.org/anything/params?param=1&param=2`, но и `https://httpbin.org/anything/params?param[]=1&param[]=2` (важно для php, например)

**Comment by vbondarevsky** [comment]
> Возможно, опционально. В общем,
> 
> ```bsl
> ПараметрыЗапроса = Новый Структура;
> ПараметрыЗапроса.Вставить("param", СтрРазделить("1,2", ","));
> 
> Ответ = КоннекторHTTP.GetJson("https://httpbin.org/anything/params", ПараметрыЗапроса);	
> ```
> 
> должна быть возможность отправить не только `https://httpbin.org/anything/params?param=1&param=2`, но и `https://httpbin.org/anything/params?param[]=1&param[]=2` (важно для php, например)

Уже можно. Нужно использовать ```Соответствие```
```bsl
ПараметрыЗапроса = Новый Соответствие;
ПараметрыЗапроса.Вставить("param[]", СтрРазделить("1,2", ","));
	
Ответ = КоннекторHTTP.GetJson("https://httpbin.org/anything/params", ПараметрыЗапроса);
```
