### ISSUE TITLE
Отправка запроса портит переданные настройки, что мешает в некоторых случаях

### ISSUE THREAD

**Issue by FragsterAt** [vbondarevsky/Connector#33]
При выполнении кода:

```bsl
Сервер = "https://jsonplaceholder.typicode.com/";

Настройки = Новый Структура; 
Заголовки = Новый Соответствие;
Заголовки.Вставить("Content-Type","application/json");
Настройки.Вставить("Заголовки", Заголовки);
//ПараметрыЗапроса = Новый Структура("username, password", "anonymous", "hrgesf7HDR67Bd");
ПараметрыЗапроса = "{""username"":""anonymous"",""password"":""anonymous""}";

НастройкиКопия = ЗначениеИзСтрокиВнутр(ЗначениеВСтрокуВнутр(Настройки));
Результат = КоннекторHTTP.Post(Сервер + "posts", ПараметрыЗапроса, НастройкиКопия);

Запись = Новый ЗаписьJSON();
Запись.УстановитьСтроку();
ЗаписатьJSON(Запись, Настройки);
Дамп1 = Запись.Закрыть();
Запись.УстановитьСтроку();
ЗаписатьJSON(Запись, НастройкиКопия);
Дамп2 = Запись.Закрыть();
```

Видно, что настройки модифицируются. Это ведет к тому, что при последовательном использовании (например post и postjson) одной структуры с настройками возможны проблемы. Собственно, я их и получил, иначе сюда бы не писал.

**Comment by VolAll** [comment]
у меня что то подобное произошло,  пришлось закомментировать в ЗаголовкиПоУмолчанию()  строку
// Заголовки.Вставить("Accept-Encoding", "gzip")

**Comment by FragsterAt** [comment]
@VolAll ну, я обошел созданием функции, которая каждый раз возвращает новый экземпляр настроек. Еще можно передавать в методы коннектора "клон", полученный из настроек с помощью `ЗначениеИзСтрокиВнутр(ЗначениеВСтрокуВнутр(Настройки))`
