### ISSUE TITLE
Есть ли версия библиотеки в англоязычном синтаксисе?

### ISSUE THREAD

**Issue by leandr92** [vbondarevsky/Connector#46]
Доброго времени суток! Хочу использовать библиотеку в разработке для зарубежных конфигураций, и русский язык там не очень подходит. Может есть какая-то инфа по англоязычным форкам, или планы на перевод кода?

**Comment by vbondarevsky** [comment]
Сейчас вроде ничего нет. Планы есть, но пока времени нет

**Comment by leandr92** [comment]
Сделал репу, где работаю над переводом. Уже сделал перевод общего модуля и частично обработки.
https://github.com/leandr92/HTTPConnector1C

**Comment by slaxxals** [comment]
Привет. Версия на английском уже есть, но пока в этом PR [https://github.com/vbondarevsky/Connector/pull/79](url)

Переведено все, кроме комментариев к методам и README.

**Comment by vbondarevsky** [comment]
Теперь есть english версия.
@slaxxals Спасибо!
