### ISSUE TITLE
Сборка проекта в формате cfe для использования впакетном менеджере А1И

### ISSUE THREAD

**Issue by malikov-pro** [vbondarevsky/Connector#49]
**Существует проблема**
Остутствует возможность загружать в базу расширение с модулем Коннектор, в дальнейшем оперативно проверять обновляения и при необходимости загружать свежую версию.

**Хотелось бы иметь следующую функциональность**
Собрать cfe с префиксом, для минимизации пересечений по имени модуля при использовании в соседних расширениях.

Сформировать описание пакета с сылками на проверки, для того чтобы при работе из 1С можно было получить общую информацию о состоянии пакета.

**Дополнительный контекст**
Развернуто мысль описал в http://forum.infostart.ru/forum9/topic249947/message2537570/

**Comment by vbondarevsky** [comment]
Расширение будет публиковаться в релизах
Для текущего релиза прямая ссылка
https://github.com/vbondarevsky/Connector/releases/download/v2.1.3/Connector_v2.1.3.cfe
