### ISSUE TITLE
Не работает метод КакJson

### ISSUE THREAD

**Issue by unveng** [vbondarevsky/Connector#55]
Метод по сути возвращает десериализованное тело ответа, а не структуру/соответствие.

**Comment by asosnoviy** [comment]
Дайте пример плз, того что не так

**Comment by unveng** [comment]
попробуйте выполнить метод PostJson. Там используется эта функция. Верните что-нибудь в теле ответа и вы увидите, что Ответ = Телу ответа, а не структуре

**Comment by vbondarevsky** [comment]
> попробуйте выполнить метод PostJson. Там используется эта функция. Верните что-нибудь в теле ответа и вы увидите, что Ответ = Телу ответа, а не структуре

На этот метод есть тест и он работает
https://github.com/vbondarevsky/Connector/blob/ed95515f49e2c4c6015d6885ae675d696d38553e/src/DataProcessors/%D0%A2%D0%B5%D1%81%D1%82%D1%8B/Ext/ObjectModule.bsl#L517

**Comment by vbondarevsky** [comment]
Пока закрываю. Если появится способ воспроизведения, то issue можно будет переоткрыть или завести новое
