### ISSUE TITLE
Авторизация по Api-Key

### ISSUE THREAD

**Issue by Mikhail-Kobtsev** [vbondarevsky/Connector#56]
Привет, подскажи, есть ли возможность создать сессию пользователя имея ключ Api?

То есть авторизовав пользователя по ключу, 
мы имеем Токен, который необходимо передавать в другие запросы....

**Comment by vbondarevsky** [comment]
> Привет, подскажи, есть ли возможность создать сессию пользователя имея ключ Api?
> 
> То есть авторизовав пользователя по ключу,
> мы имеем Токен, который необходимо передавать в другие запросы....

Если токен передается в заголовках, то можно задать этот заголовок у сессии и он будет передаваться во все вызовы
