### ISSUE TITLE
Показывать исходную проблему при ошибке разбора JSON в методе КакJson (GetJson, PostJson, PutJson, DeleteJson)

### ISSUE THREAD

**Issue by antonwantstosleep** [vbondarevsky/Connector#60]
Здравствуйте! Шикарная библиотека, я даже теперь не боюсь писать код для вызова разных API, поскольку стало супер просто ))

Вот мой мелкий кейс.
1. Пока сайт (точнее его API) доступно, метод GetJson работает ок, поскольку API отдает Json.
2. Но если доступ к сайту, например, заблокировать в .htaccess, то он начинает по любому запросу отдавать html, например:
```
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>403 Forbidden</title>
</head><body>
<h1>Forbidden</h1>
<p>You don't have permission to access /wp-json/wp/v2/settings
on this server.</p>
</body></html>
```
=> библиотека крашится в функции `JsonВОбъект` на строчке `Объект = ПрочитатьJSON(`, поскольку тело ответа - не json.

Я понимаю, что это не проблема библиотеки - ведь сайт вдруг вместо json начинает отдавать html :) Но м.б. обернуть `Объект = ПрочитатьJSON` в Попытку/Исключение и вернуть, не знаю, какую-нибудь ошибку?

**Comment by artbear** [comment]
Я также столкнулся с таким поведением.

При такой ошибке на стороне вызывающего кода никак нельзя узнать об ошибке, которую вернул сайт.

например, я  при запросе к сервису 1С столкнулся  с ошибкой `Недостаточно прав для использования ресурса с данным HTTP методом`

и сам текст ошибки смог увидеть только в режиме отладки, по-другому средствами данной библиотеки его не достанешь (

@vbondarevsky я готов сделать ПР

**Comment by artbear** [comment]
Обсуждение из телеграма https://t.me/ssl1c/80330

Кирилл Черненко, [18.03.21 00:14]
[In reply to Artur Ayukhanov]
Почему нельзя? Получить тело как текст и узнать таки что выдает сайт

Artur Ayukhanov, [18.03.21 00:15]
[In reply to Кирилл Черненко]
это можно ,конечно, но если юзать методы-обертки из АПИ для json, то нельзя )
т.е. получается, что эти методы в проде юзать нельзя, т.к. могут упасть при проблемах, а суть проблемы ты никак не узнаешь.
если же переписать код без их использования, зачем они тогда нужны? )

Artur Ayukhanov, [18.03.21 00:17]
или каждый вызов таких методов обмазывать попытками и чтением тела не очень солидно, когда это можно сделать внутри самой библиотеки

Кирилл Черненко, [18.03.21 00:18]
[In reply to Artur Ayukhanov]
А какое решение ты видишь? Можно конечно прочитатьJson завернуть в попытку и если упал в исключение ВызыватьИсключение с текстом из тела ответа (правда там могут быть хтмлки от сайта и в ЖРе это будет так себе анализировать), ну или все тело упаковать в структуру со свойством "error_message" или типа того и возвращать его

Artur Ayukhanov, [18.03.21 00:21]
[In reply to Кирилл Черненко]
ну да, завернуть в попытку и писать в ЖР или еще куда тело ответа
и вызывать исключение

Artur Ayukhanov, [18.03.21 00:23]
тут можно 
- либо писать в ЖР с телом реального ответа и подробным представлением ошибки и просто ВызватьИсключение; (проброс ошибки наверх)
- Либо запись в ЖР с телом реального ответа и подробным представлением ошибки
и ВызватьИсключение с эти же телом

вариант с упаковкой в структуру так себе, т.к. мы при этом нарушаем контракт, получатель-то ожидает ответ в нужном для него формате, а не наш.
да и ситуация исключительная

Кирилл Черненко, [18.03.21 00:29]
[In reply to Artur Ayukhanov]
Можно, правда ковырять хтмлки в ЖРе такое себе удовольствие но а целом решение.
Со структурой это вариант для того что бы дать принимающей стороне возможность самостоятельно разрулить ситуацию, что-то типа:
Объект = JsonВОбъект();
ПроверитьВозвратВебСервиса(Объект); // тут проверка это структура с ошибкой и возможно внутри вызов исключения
Далее всякий бизнес код

**Comment by artbear** [comment]
Возможно, ПР https://github.com/vbondarevsky/Connector/pull/64 частично может решить проблему, если передавать метод-обработчик исключения
