### ISSUE TITLE
Получение тела как строки в новых версиях.

### ISSUE THREAD

**Issue by Shadawn** [vbondarevsky/Connector#65]
В старых версиях (1.2.3) в структуре ответа был ключ "Ответ", содержащий встроенный объект 1С типа HTTPОтвет. Соответственно, я мог получить строковое тело ответа с как СтруктураОтвета.Ответ.ПолучитьТелоКакСтроку(); В актуальной версии это не работает так как ключа "Ответ" нет.

Прошу уточнить - это плановое изменение или регрессия. Если плановое, то как предполагается работать с текстовыми ответами?

**Comment by vbondarevsky** [comment]
Правильный способ:
```Строка = КоннекторHTTP.КакТекст(Ответ);```

При желании можно ```Ответ.Тело``` прочитать с строку
