### ISSUE TITLE
Тесты требуют наличия действующего аккаунта ИТС

### ISSUE THREAD

**Issue by leemuar** [vbondarevsky/Connector#7]
В данный момент чтобы запустить и проверить прохождение тестов, требуется действующий аккаунт ИТС. Это немного усложняет доработку библиотеки, у некоторых разработчиков (типа меня) аккаунта нет.

Возможно стоит сделать так, чтобы запуск и прохождение теста не зависели от наличия у тестирующего действующего аккаунта ИТС. httpbin вроде умеет работать с куками, его возможностей будет достаточно для того чтобы этот тест сделать?

![image](https://user-images.githubusercontent.com/5869791/53247829-5e4be480-36c5-11e9-91a1-0f336fdaff96.png)

**Comment by vbondarevsky** [comment]
Логин и пароль действующие?
Проверил, у меня работает.

**Comment by leemuar** [comment]
Логин и пароль не действующие.

Переформулирую проблему: сделать так, чтобы запуск и прохождение теста не зависели от наличия у тестирующего действующего аккаунта ИТС. httpbin вроде умеет работать с куками, его возможностей будет достаточно для того чтобы этот тест сделать?

**Comment by vbondarevsky** [comment]
Тест с аутентификацией на сайте 1С убрал под флаг, добавил отдельный тест для работы с сессиями
