### ISSUE TITLE
Метод JsonВОбъект требует доработки

### ISSUE THREAD

**Issue by Nytlenc** [vbondarevsky/Connector#77]
Требуется добавить вот такое условие, в противном случае при передачи JSON в виде строки возникает ошибка

![image](https://user-images.githubusercontent.com/84758792/132093649-da3b2c72-bd4c-4d69-b22a-d24a6af3c901.png)

**Comment by vbondarevsky** [comment]
Видимо у вас какая-то старая версия.
В мастере все это есть
https://github.com/vbondarevsky/Connector/blob/8317e43fe05e7f7ae058668635ed205ebc221085/src/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L763
