### ISSUE TITLE
Аккуратно обрабатывать ответы с пустым телом для методов КакойТоМетодJson

### ISSUE THREAD

**Issue by vbondarevsky** [vbondarevsky/Connector#80]
http://forum.infostart.ru/forum9/topic182385/message2709746/#message2709746

> Не всегда чей то API может возвращать чтото в теле ответа, При этом все в JSON. К примеру Обертка MongoDB на RestHeart при отправке POST запроса вернет только код 201 ОК. При этом коннектор упадет в исключение при попытке сериализации пустого тела в JSON

Как вариант в таких случаях возвращать Неопределено/Новый Структура/Новый Соответствие

**Comment by zeegin** [comment]
см #95

**Comment by leemuar** [comment]
Считаю что необходимость не достаточно обоснована.
Методы с суффиксом Json - это хелперы, призванные упростить код там где точно приходит JSON. Использовать их стоит там где ты точно уверен в возвращаемом формате. Не уверен, может приходить что-то другое - не надо их использовать. Лучше брать пару ```Метод() + Если +  КакJson()```

Возврат ```Неопределено``` при пустом коде не улучшит код по сравнению с ```Метод() + Если +  КакJson()```, поэтому имхо не стоит это реализовывать. По крайней мере пока не появятся более весомые аргументы

**Comment by zeegin** [comment]
Я считаю что зря закрыл.
Можно было докрутуть до большей полезности хелпера.
Например сделать праметр необязательный со значением по умолчанию в случае ошибки.

**Comment by zeegin** [comment]
Пример с монго от Володи прям живой)

**Comment by leemuar** [comment]
> до большей полезности хелпера

@zeegin Нужны аргументы и критерии оценки полезности. Я не вижу бенефитов. Но может есть примеры, о которых я не знаю, где эта полезност будет очевидная. Приведи примеры кода без этой функциональность и такой же пример примеры с ней, в чем будет заключаться полезность.
