### ISSUE TITLE
Неверно отрабатывает повтор

### ISSUE THREAD

**Issue by permblackshark** [vbondarevsky/Connector#92]
При повторе запроса, не скидывается ОшибкаВыполненияЗапроса.
Необходимо инициализировать ОшибкаВыполненияЗапроса = Неопределено в начале цикла в Функция ОтправитьЗапрос

Пока Истина Цикл
		ОшибкаВыполненияЗапроса = Неопределено;

		Попытка
			Ответ = ОтправитьHTTPЗапрос(Сессия, ПодготовленныйЗапрос, Настройки);
		Исключение
			ОшибкаВыполненияЗапроса = ИнформацияОбОшибке();
		КонецПопытки;

**Comment by leemuar** [comment]
Починили в https://github.com/vbondarevsky/Connector/pull/142/
