### ISSUE TITLE
Сделать маскировку конфиденциальных данных перед их возвратом

### ISSUE THREAD

**Issue by zeegin** [vbondarevsky/Connector#94]
Хочется чтобы перед записью в ЖР и показу пользователю вырезались чувствительные данные типо паролей токенов и т.п.
Нужен некоторых общий механизм постобработки результата в виде хука или вариант декларативного описания обработки.

Надо думать как это сделать удобно.

**Comment by leemuar** [comment]
имхо логирование - не ответственность библиотеки. Если вам такое нужно - лучше сделать обертку над библиотекой с нужной вам функциональностью

**Comment by zeegin** [comment]
@leemuar тогда надо из библиотеки вырезать все записи в журнал) это же не ее ответственность...

Вообще хорошая практика это давать точку интеграции пред записью в журнал чтобы я мог сделать декоратор который сокроет то что мне нужно. Или вообще отключить логгирование.

**Comment by leemuar** [comment]
@zeegin покажите, пожалуйста, строку в библиотеке, пишущую в журнал. Возможно я что-то пропустил

**Comment by leemuar** [comment]
Дубликат #89

**Comment by zeegin** [comment]
> @zeegin покажите, пожалуйста, строку в библиотеке, пишущую в журнал. Возможно я что-то пропустил

https://github.com/vbondarevsky/Connector/blob/735bd71b1f8b8c32c73b597e81d8dda172fd1920/src/ru/CommonModules/%D0%9A%D0%BE%D0%BD%D0%BD%D0%B5%D0%BA%D1%82%D0%BE%D1%80HTTP/Ext/Module.bsl#L679C5-L679C5


Мы формируем текст исключения из ответа. Исключения записываются в журнал. Ответ - попадет в журанл. Ответ может содержать чувствительные данные которые не должны попасть в лог.

**Comment by leemuar** [comment]
@zeegin тут же нет записи в журнал регистрации? То что вы показываете - это формирование текста исключения. Здесь библиотека поступает верно - просто пробрасывает исключение в вызывающий ее код. Что с ним дальше делать - ответственность пользовательского кода, не библиотеки. Если не оборачивать вызов Коннектора в Попытку и позволять необработанному исключению прорасти на уровень обработки платформой (которая и запишет исключение в ЖР) - это ошибка пользовательского кода, а не библиотеки. Так не стоит делать, и модифицировать поведение библиотеки под такой код - тоже. 

При этом я не оспариваю необходимость иметь точку расширения, позволяющую как-то что-то сделать (логировать, санитайзить и т.п.) с запросом до и после выполнения. Я лишь призываю к конструктивному поиску способа решения, с учетом особенности библиотеки и платформы.

Можно, например, ТекстИсключения модифицировать расширением конфигурации. Это довольно стандартный способ для 1С, но и не без недостатков.

Какой способ вы бы предложили?

**Comment by zeegin** [comment]
@leemuar 
> Какой способ вы бы предложили?

Оборачивать все в попытку исключения - и там подчищать / изменять тексты исключений 
до записи в журнал - возможный вариант.

Когда делаешь поставляемое решение то его надо сделать встроенным, потому решение с расширениями не подходит.

Еще возможный вариант - сделать переопределяемый интерфейс в который будет бросаться текст исключения после обработки библиотекой для подчистки.

Еще один вариант это пропатчить функцию КакИсключение для себя и аккуратно мержевать новую версию библиотеки.

**Comment by leemuar** [comment]
`Еще один вариант это пропатчить функцию КакИсключение для себя и аккуратно мержевать новую версию библиотеки.`

Это как раз делается расширениями. Вы учитывайте, что библиотека статичная, это лишь набор функций, она не хранит состояние. Расширения - стандартный способ в платформе вносить изменения.

Что вы имеете в виду под "переопределяемый интерфейс"? Звучит как общая идея, дайте больше конкретики - кк это во встроенном языке реализовать?

**Comment by zeegin** [comment]
@leemuar 
> Что вы имеете в виду под "переопределяемый интерфейс"? Звучит как общая идея, дайте больше конкретики - как это во встроенном языке реализовать?

https://its.1c.ru/db/v8std#content:553:hdoc

**Comment by leemuar** [comment]
@zeegin понятно, спасибо! Выглядит легко реализуемым. Со своими недостатками, конечно

**Comment by leemuar** [comment]
Закрываю как частный случай логирования, будем решать в #89
