### ISSUE TITLE
Пометить как устаревшие методы GetJson, PostJson и аналогичные

### ISSUE THREAD

**Issue by zeegin** [vbondarevsky/Connector#95]
Мне эти методы не нравятся тем, что они берут на себя очень много. Они и сериализуют и десериализуют. Это часто приводит к ошибкам:
1. не надо отправлять в json
2. не надо читать в json
3. может прийти не json в случае ошибки

В итоге все сводится к тому что это инструмент очень спорный очень точечно применяемый и лучше его не иметь чем иметь.

Хочется строить флюент конструкции, а не иметь множество методов с разными суффиксами.

Предлагаю отметить методы как устаревшие и в версии 3.0 их удалить.

**Comment by artbear** [comment]
Согласен, эти методы неверно работают, если в ответе приходит не json, и не логируются.

**Comment by vbondarevsky** [comment]
> Хочется строить флюент конструкции, а не иметь множество методов с разными суффиксами.

Ты знаешь как это сделать оставаясь в рамках одного модуля?)

> Предлагаю отметить методы как устаревшие и в версии 3.0 их удалить.

Скорей согласен. Посмотрим, может кто-то придет с весомыми аргументами

**Comment by zeegin** [comment]
Можно сделать за счет блоба внешней обработки которую компилить и подключать на лету. Но это геморой тот еще такое поддерживать.

**Comment by sfaqer** [comment]
> Хочется строить флюент конструкции, а не иметь множество методов с разными суффиксами.

\+

**Comment by nixel2007** [comment]
> Ты знаешь как это сделать оставаясь в рамках одного модуля?)

перенести все из общего модуля в обработку.

**Comment by nixel2007** [comment]
> В итоге все сводится к тому что это инструмент очень спорный очень точечно применяемый и лучше его не иметь чем иметь.

я вот этот тезис не совсем понимаю. мне кажется удобным иметь метод отправки гет-запроса, который сразу десерилизует ответ. мне с чистым json'ом все равно делать нечего, объект модели нужен.

то, что он не логируется (если это действительно так) - это проблема, конечно.
а то, что он падает, если в ответе не json - вроде логично, не? запросили валидный ответ, получили херню. исключительная ситуация, надо падать.

**Comment by zeegin** [comment]
Часто в ответ приходят структуры разные по составу для ошибки или для правильного ответа. Это могут быть либо json с разными схемами либо при ошибке просто текст.

Я пока не нашел ниодного применения метода когда я гарантированно должен либо получить json ожидиемой структуры либо упасть в исключение.

Всегда приходилось делать обработку дополнительную либо по заголовку либо по коду состояния либо анализировать тело ответа.

Возможно эти методы в каких-то редких случаях применимы, но суть пассажа о том что лучше не иметь отдельные методы на такие редкие случаи чем иметь. Потому что чем меньше инструментов тем меньше шанс допустить в них ошибку и меньше надо знать нюансов их работы.

@nixel2007

**Comment by sfaqer** [comment]
> Можно сделать за счет блоба внешней обработки которую компилить и подключать на лету. Но это геморой тот еще такое поддерживать.

А зачем гемороится с поддержкой? Поидее нужно просто пилить обработку и уже при сборке релиза упаковывать ее внутрь ОМа. Так поидее никаких проблем с поддержкой не будет

**Comment by zeegin** [comment]
Ну нужно еще понимать что возможно будут ухудшения на производительности за счет создания доп объектов в памяти. И еще не будет удобного автокомплита.

Мне больше нравится идея сделать все в общем модуле, но при этом сделать расширение которое позволит использовать флюент поверх. При этом сделать так чтобы модуль был необходим, а обработки добавляли те, кто хочет. Типо ограниченная и полная поставка. При этом фактических преимущества обарботки кроме флюента не давали.

**Comment by nixel2007** [comment]
да зачем вообще модуль? обработка как нормально настроенный объект, методы которого возвращают this. тут и сеттеры настроек человеческие, и проверки корректности, и флюент. к чему этот static hell на общих модулях?

**Comment by sfaqer** [comment]
> да зачем вообще модуль? обработка как нормально настроенный объект, методы которого возвращают this. тут и сеттеры настроек человеческие, и проверки корректности, и флюент. к чему этот static hell на общих модулях?

Кмк что не было ада тут нужно две обработки, одна отвечает за запрос вторая за ответ, иначе смешение контекста будет лютое

**Comment by leemuar** [comment]
Не вижу в этих методах ничего устаревшего или плохого. Это хелперы, хорошие и полезные. Такие же, как метод ok() в библиотеке requests.
Использовать их или нет - это выбор разработчика. Понимать что в ответ может приходить что-то другое и писать соответствующий код - ответственость разработчика, не библиотеки. Библиотека здесь не должна ничего диктовать.

**Comment by zeegin** [comment]
ок будем не использовать :)
